### ISSUE TITLE
ブルスク問題 2023-12-02

### ISSUE THREAD

**Issue by fltuna** [fltuna/my-pc-issues#1]
KMODE_EXCEPTION_NOTHANDLED (netio.sys)を吐いてかなり頻繁にクラッシュする

確認事項
- [ ] メモリ破損の確認
- [x] 怪しいドライバ/ソフトウェアのアンインストール

**Comment by fltuna** [comment]
VRChatをVRで起動中にもブルースクリーンを何度か吐いてて、HMD付けてるためエラーの内容は未確認。

**Comment by fltuna** [comment]
とりあえずAsusのarmoury crateとIntel Driver & Assistant Supportが一緒にインストールされてたのでIntel Driver & Assistant Supportをアンストして様子見
（リンク先の例外名はSYSTEM_THREAD_EXCEPTION_NOT_HANDLEDであるが同じ環境だったので試してみた)
https://answers.microsoft.com/en-us/windows/forum/all/windows-11-bluescreen-netiosys-solved/e627f67b-ee78-4e73-a969-d645a642bce3

**Comment by fltuna** [comment]
正直な話電源がもう5年も使ってるのでフル稼働時に電圧を維持できていない可能性

todo
- [ ] 電圧を図る方法を調べる

**Comment by fltuna** [comment]
とりあえず今から寝て、起きた時にクラッシュしてないかを確認しよう

**Comment by fltuna** [comment]
> 正直な話電源がもう5年も使ってるのでフル稼働時に電圧を維持できていない可能性
> 
> todo
> 
> * [ ]  電圧を図る方法を調べる

今の接続デバイス数増えたから消費電力増えた？

デバイスリスト 
(PCから直接給電)
* Komplete Audio 2
* Wacomの板タブ

(外部電源付き)
* Pico 4 with PD
* Topre GX 1
* Logicool G604
* iPhoneの充電ケーブル
* (たまに) Dual Sense

増えてなさそう、てかむしろ外部電源付きHubを買ったから減ったのでは？

**Comment by faketuna** [comment]
書き忘れてたけど一先ず問題なさそう

**Comment by fltuna** [comment]
> とりあえず今から寝て、起きた時にクラッシュしてないかを確認しよう

書き忘れてたけど一先ず問題なさそう

**Comment by fltuna** [comment]
明日VRで動作を確認してクラッシュしなかった場合は
> とりあえずAsusのarmoury crateとIntel Driver & Assistant Supportが一緒にインストールされてたのでIntel Driver & Assistant Supportをアンストして様子見

で行ったように、Asusのarmoury crateとIntel Driver & Assistant Supportの相性が悪いことが原因であるとほぼ確定できる

**Comment by fltuna** [comment]
クラッシュは特に発生しなかったので解決とする

**Comment by fltuna** [comment]
原因違ったわ。最終的な原因判明

Pico 4とPCをadb使ってRNDISを有効化してVDで接続するようにすると確実に落ちる。 おそらく他のソフトウェアとの競合が発生してる可能性が高いがこれをチェックするのはほぼ難しいと思うので有線接続をしないようにしよう

**Comment by fltuna** [comment]
細かく調べた感じだと、WindowsのRNDISドライバはWindows 10のバージョン1709 (Fall Creators Update)からRNDISドライバ関連の仕様変更が相次いでいて、それに各社のドライバが対応できていないみたい。
